### ISSUE TITLE
https://aop.wikipathways.org/ is not working well

### ISSUE THREAD

**Issue by egonw** [wikipathways/wikipathways.org#38]
But http://aop.wikipathways.org/ is working...

The HTTPS variant gives a security warning in Chrome:

![image](https://user-images.githubusercontent.com/26721/36470963-0ae58d3a-16ed-11e8-9a92-4f190c6c0763.png)

Nuno, got a quick fix for this in mind?

**Comment by egonw** [comment]
cc @marvinm2

**Comment by AlexanderPico** [comment]
We have about 13 redirects to WikiPathways pages like this. The explicit https for them has never worked. Always just typed the url is plain and the redirect just happens.

In order to support explicit https prefixes on these redirects, we'll have to restructure how we do them... @nunogit Currently they are each their own apache conf file. Should they be in htaccess instead? Or is there a simple fix to the apache conf?  It looks like this currently:

```
<VirtualHost *:80>
        ServerName aop.wikipathways.org
        ServerAlias aop.wikipathways.org
        Redirect / http://www.wikipathways.org/index.php/Portal:AOP
</VirtualHost>

```

**Comment by Mse-lunani** [comment]
try just using 
` Redirect wikipathways.org/index.php/Portal:AOP`

**Comment by nunogit** [comment]
@AlexanderPico @egonw  being on .htaccess will not solve it.

But why don't we just redirect o https:// instead of http://

We get errors with https because currently lets encrypt does not support wildcards on domains *.wikipathways.org

If  we want to use https we need to request individual certificates for each subdomain. Since it's free and easy we can easily achieve it. We can even make a small script to automate the process.

**Comment by hexmode** [comment]
nunogit writes:

> We get errors with https because currently lets encrypt does not
> support wildcards on domains *.wikipathways.org

Lets Encrypt supports wildcards as of March 13 this year:
https://community.letsencrypt.org/t/acme-v2-and-wildcard-certificate-support-is-live/55579

**Comment by nunogit** [comment]
Thanks for the tip. That's really new.

> Additionally, wildcard domains must be validated using the DNS-01 challenge type. This means that you’ll need to modify DNS TXT records in order to demonstrate control over a domain for the purpose of obtaining a wildcard certificate.

In any case it requires DNS access We have to orchestrate this with Alex to get it.
Otherwise if it's just "half a dozen" domains it's just better to request individual ones.

**Comment by egonw** [comment]
It was discussed and decided too much work at this moment. We keep using the http:// links for the shortcuts, which redirect to https:// anyway.

**Comment by Chris-Evelo** [comment]
Did you mean "was discussed" before or after this news?

**Comment by egonw** [comment]
Before :) In the WikiPathways telcon of last week? Or maybe the one before that already.
