### ISSUE TITLE
Step through new author training at WikiPathways Academy

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/wikipathways.org#49]
We need more folks to go through the interactive training material we prepared to: 

1. Become a pathway editor, or
2. Provide feedback on the system, or
3. Propose new training elements, or
4. Implement new training elements.

Start here: https://wikipathways.github.io/academy/

**Comment by DeniseSl22** [comment]
I'm going through the academy now. First points:
Change the text of Biology 101 - Gene Products to:

Within your DNA, all relevant information is stored to build and maintain your body. From a template of your DNA (which we call a gene),  RNA is produced in a process called transcription. The RNA then serves as a template for the production of a protein through the process of translation. RNA and proteins are called "Gene Products", since they are coded for by genes in your DNA.

Because RNA is transcribed from DNA, and because a protein is translated from RNA, a mutation in DNA can affect both RNA and protein gene products. This is how a genetic mutation can result in changes to protein function and, thus, cellular function.

Proteins are the main components of many cellular functions, such as metabolism. Metabolic pathways are a series of chemical reaction mostly carried out by protein enzymes. The chemical reactants and products in metabolic pathways are called "Metabolites". Metabolites are often molecules like lipids, sugars, cholesterol, and amino acids.

Explanation
That’s correct! And WikiPathways allows you to specify molecule types as you draw a pathway. We use the “Gene Product” type to mean either RNA or protein, and the "Metabolite" type to refer to a small chemical.

**Comment by DeniseSl22** [comment]
Biology 101 - Metabolites:

Question does not fit with text described there (you need to know some biology to get the question right). Perhaps we could include an example drawing, going from one metabolite to another with help of an enzyme, and then ask which one the product is (a term familiar to biologists and chemists)?

**Comment by DeniseSl22** [comment]
Biology 101 - Metabolic Pathway

The linkouts in the background refer to Wikipedia, I would like to see the link to a PW from WPs...

**Comment by DeniseSl22** [comment]
Cholesterol Biosynthesis - Overview

Add a linkout to cholesterol PW, not to Wikipedia

**Comment by DeniseSl22** [comment]
Cholesterol Biosynthesis - First Conversion

One of the answers cannot be true, I would change the possible answers to the following:
- HMGCS1
- HMG-CoA
- Beta-oxidation
- cholesterol

**Comment by DeniseSl22** [comment]
Just found the code (https://github.com/wikipathways/academy); will fork this and make the changes myself :)

**Comment by AlexanderPico** [comment]
Why fork when you can edit directly! You are a developer of that repo already.  Saves the step of a pull request :)

**Comment by khanspers** [comment]
done
