### ISSUE TITLE
Can't download BioPAX files

### ISSUE THREAD

**Issue by need47** [wikipathways/wikipathways.org#83]
Go to https://www.wikipathways.org/index.php/Daily_Download, and click any of the links under BioPAX, I got a page with the following error:

Error
Couldn't convert file type: owl

Please help fix it. Thank you.

**Comment by AlexanderPico** [comment]
Hi. I asked around but did not find anyone working on this bug on the current site. The main reason being that we are focused on a major updgrade to the underlying MediaWiki at the moment. This function will be working in the new version, which we hope to have out in the coming months.

In the meantime, perhaps you can explain your use case and we can suggest an alternative. Frankly, the OWL format has been our least requested/used. It's also one of the poorest in terms of loss of information. So, I wonder if an alternative format would serve you better. For example: wikidata, RDF, and GMTs are popular alternatives to our native GPML format.  

Please feel free to follow up on the helpdesk for advice on our better supported formats:
https://groups.google.com/forum/#!forum/wikipathways-discuss

I'm going to close this ticket since this feature won't likely be fixed in this codebase.

**Comment by need47** [comment]
That's because I already have a BioPAX3 parser. Now I'm looking at the native GPML format. Which version of schema is currently being used? I found there are a number of them: https://github.com/PathVisio/GPML. The most recent one seems to be GPML2017. But the downloaded xml file does specify any xsd info, e.g. the one download from here: https://www.wikipathways.org/index.php/Pathway:WP534

**Comment by AlexanderPico** [comment]
@mkutmon @egonw 
I think our current GPML are 2013a. I'm cc'ing others who might be able to advise on using our GPML and RDF for your use case, which is???

**Comment by need47** [comment]
Thanks. I will use the native GPML format. In our use case, we'd like to parse out the "interactions" out of a pathway, as well as the protein/genes/chemicals involved in it.

**Comment by AlexanderPico** [comment]
We've already done most of the hard work to extract out meaningful interactions from the GPML and modeling them as RDF. I suspect that format is going to be the most direct, efficient and high-quality source. 

You can see, for example, some SPARQL queries that are supported by our GPML-RDF data: https://www.wikipathways.org/index.php/Help:WikiPathways_Sparql_queries#Interaction_oriented_queries
